site_name: Nebula Pad with Ender-3 v3 SE
theme:
  name: material
  palette:
    primary: green
  features:
    - content.code.copy
markdown_extensions:
  - admonition
  - sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Setup: SettingUpNebulaPad/SettingUpNebulaPad.md
  - General:
      - Formatting SD: GeneralTutorials/FormatingSDCard.md
      - SSH: GeneralTutorials/SSHIntoNebulaPad.md
      - Api Token: GeneralTutorials/GettingAPITokenForRemotePrinting.md
  - Rooting:
      - Downgrading: RootingNebulaPad/DowngradingNebulaPad.md
      - Installing: RootingNebulaPad/InstallingRootedFirmware.md
  - Fixes: FixesForNebulaPad/FixesForNebulaPad.md
  - OcraSlicer:
      - Installation: OcraSlicer/InstallingOcraSlicer.md
      - Setting Up Printer Profile: OcraSlicer/SettingUpPrinterProfile.md
      - Setting Up Remote Printing: OcraSlicer/SettingUpRemotePrinting.md
      - Setting Up Process Profile: OcraSlicer/SettingUpProcessProfile.md
      - Setting Up Filament Profile: OcraSlicer/SettingUpFilamentProfile.md
  - Security: SECURITY.md