# Project Info
site_name: Nebula Pad with Ender-3 v3 SE

# Configuration
theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# Plugins
plugins:
  - glightbox

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - sane_lists

# Page Tree
nav:
  - safety.md
  - Home: index.md
  - Setup: setup-nebula-pad/index.md
  - Rooting and Fixes:
    - Rooting the Nebula Pad: rooting/index.md
    - Post-Root Fixes: rooting/fixes/index.md
  - General:
    - Formatting SD: general/format-sd.md
    - SSH: general/nebula-pad-ssh.md
    - Api Token: general/fluidd-api-token.md
    - Finding Printer IP:  general/find-ip.md
    - Recommended Tools: general/tools.md
  - OrcaSlicer:
    - Installation: orca-slicer/installing.md
    - Setting Up:
      - Printer Profile: orca-slicer/setup/printer-profile.md
      - Remote Printing: orca-slicer/setup/remote-printing.md
      - Process Profile: orca-slicer/setup/process-profile.md
      - Filament Profile: orca-slicer/setup/filament-profile.md
  - Addons:
    - Ceramic Hot End Kit: addons/ceramic-hot-end.md
    - Linear Guide Rail: addons/linear-guide-rail.md
    - LED Light Bar:
      - Installation: addons/lightbar.md
      - Tips: addons/lightbar-tips.md
