# Project Info
site_name: Nebula Pad with Ender-3 v3 SE

# Configuration
theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections
  palette:
    primary: green

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - sane_lists

# Page Tree
nav:
  - safety.md
  - Home: index.md
  - Setup: setup-nebula-pad/index.md
  - Rooting and Fixes:
    - Rooting the Nebula Pad: rooting/index.md
    - Post-Root Fixes: rooting/fixes/index.md
  - General:
    - Formatting SD: general/format-sd.md
    - SSH: general/nebula-pad-ssh.md
    - Api Token: general/fluidd-api-token.md
    - Getting Printer Ip:  general/find-ip.md
  - OrcaSlicer:
    - Installation: orca-slicer/installing.md
    - Setting Up:
      - Printer Profile: orca-slicer/setup/printer-profile.md
      - Remote Printing: orca-slicer/setup/remote-printing.md
      - Process Profile: orca-slicer/setup/process-profile.md
      - Filament Profile: orca-slicer/setup/filament-profile.md
