# Project Info
site_name: Nebula Pad with Ender-3 v3 SE

# Configuration
theme:
  name: material
  features:
    - content.code.copy
  palette:
    primary: green

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - sane_lists

# Page Tree
nav:
  - Home: index.md
  - Setup: SettingUpNebulaPad/SettingUpNebulaPad.md
  - General:
      - Formatting SD: GeneralTutorials/FormatingSDCard.md
      - SSH: GeneralTutorials/SSHIntoNebulaPad.md
      - Api Token: GeneralTutorials/GettingAPITokenForRemotePrinting.md
      - Getting Printer Ip:  GeneralTutorials/GettingPrinterIp.md
  - Rooting:
      - Downgrading: RootingNebulaPad/DowngradingNebulaPad.md
      - Installing: RootingNebulaPad/InstallingRootedFirmware.md
  - Fixes: FixesForNebulaPad/FixesForNebulaPad.md
  - OcraSlicer:
      - Installation: OcraSlicer/InstallingOcraSlicer.md
      - Setting Up Profiles:
        - Printer Profile: OcraSlicer/SettingUpPrinterProfile.md
        - Remote Printing: OcraSlicer/SettingUpRemotePrinting.md
        - Process Profile: OcraSlicer/SettingUpProcessProfile.md
        - Filament Profile: OcraSlicer/SettingUpFilamentProfile.md
  - safety.md