site_name: Nebula Pad with Ender-3 v3 SE
theme:
  name: material
  palette:
    primary: green
  features:
    - content.code.copy
markdown_extensions:
  - admonition
  - sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Setup: SettingUpNebulaPad/SettingUpNebulaPad.md
  - Rooting: 
    - Downgrading: RootingNebulaPad/DowngradingNebulaPad.md
    - Installing: RootingNebulaPad/InstallingRootedFirmware.md
  - Fixes: FixesForNebulaPad/FixesForNebulaPad.md
  - General:
    - Formatting SD: GeneralTurtorials/FormatingSDCard.md
    - SSH: GeneralTurtorials/SSHIntoNebulaPad.md
  - Security: SECURITY.md